name: Sync Upstream
on:
  schedule:
    - cron: '45 */6 * * *'    # 00:45, 06:45, 12:45, 18:45
  workflow_dispatch:

permissions:
  actions: write
  contents: write
concurrency:
  group: sync-upstream
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      UPSTREAM_REPO: '${{ vars.UPSTREAM_REPO }}'
      MAIN_BRANCH: "main"

    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ env.MAIN_BRANCH }}
          fetch-depth: 0

      - name: Get current ${{ env.MAIN_BRANCH }} commit
        id: before
        shell: bash -euo pipefail {0}
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Sync ${{ env.MAIN_BRANCH }} with upstream
        shell: bash -euo pipefail {0}
        run: |
          echo "> Add upstream remote"
          git remote add upstream https://github.com/$UPSTREAM_REPO || true
          echo "> Fetch upstream changes"
          git fetch upstream
          upstream_default_branch=$(git rev-parse --abbrev-ref upstream/HEAD)
          echo "> Update $MAIN_BRANCH with upstream $upstream_default_branch branch"
          git merge upstream/HEAD --ff-only
          git push origin $MAIN_BRANCH

      - name: Get updated ${{ env.MAIN_BRANCH }} commit
        id: after
        shell: bash -euo pipefail {0}
        run: |
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Check if ${{ env.MAIN_BRANCH }} was updated
        id: check
        run: |
          if [ "${{ steps.before.outputs.sha }}" != "${{ steps.after.outputs.sha }}" ]; then
            echo "updated=true" >> $GITHUB_OUTPUT
            echo "> $MAIN_BRANCH was updated"
          else
            echo "updated=false" >> $GITHUB_OUTPUT
            echo "> No changes from upstream"
          fi

      - name: Trigger loci-analysis workflow
        if: steps.check.outputs.updated == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash -euo pipefail {0}
        run: |
          gh workflow run \
            --repo ${{ github.repository }} \
            --ref overlay \
            -f branch=$MAIN_BRANCH \
            loci-analysis.yml
